version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: next
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-config-next
        update-types: ["version-update:semver-major"]
      - dependency-name: react
        update-types: ["version-update:semver-major"]
      - dependency-name: react-dom
        update-types: ["version-update:semver-major"]
      - dependency-name: react-leaflet
        update-types: ["version-update:semver-major"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: prisma
        update-types: ["version-update:semver-major"]
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: tailwindcss
        update-types: ["version-update:semver-major"]
      - dependency-name: vitest
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
