const COLORS={"Knowledge Hub":"#169b7b","GreenTech":"#bd7812","Mining 4.0":"#7468d4","SKA / Data":"#348bd1","Logistics":"#d4552f","Skills / Education":"#57616a","Rural / Remote":"#5a8f27"};
const state={locations:[],visible:[],selectedId:null,markers:new Map()};
const el={search:document.getElementById("searchInput"),district:document.getElementById("districtFilter"),category:document.getElementById("categoryFilter"),verified:document.getElementById("verifiedOnly"),list:document.getElementById("locationList"),count:document.getElementById("visibleCount"),empty:document.getElementById("emptyState"),reset:document.getElementById("resetButton"),fit:document.getElementById("fitResultsButton")};
const map=L.map("map",{zoomControl:true,minZoom:4}).setView([-29.3,21.5],6);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);const layer=L.layerGroup().addTo(map);
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function icon(x){const c=COLORS[x.category]||"#169b7b";return L.divIcon({className:"",html:`<div class="custom-marker" style="--marker-color:${c}"><span>${esc(x.icon)}</span></div>`,iconSize:[38,38],iconAnchor:[19,38],popupAnchor:[0,-38]})}
function popup(x){return `<article class="popup"><p class="popup-category">${esc(x.category)}</p><h3>${esc(x.icon)} ${esc(x.name)}</h3><p><strong>${esc(x.district)}</strong> · ${esc(x.municipality)}</p><p>${esc(x.summary)}</p><strong>Priority opportunities</strong><ul>${x.opportunities.map(i=>`<li>${esc(i)}</li>`).join("")}</ul></article>`}
function addMarkers(){layer.clearLayers();state.markers.clear();for(const x of state.visible){const m=L.marker([x.latitude,x.longitude],{icon:icon(x),title:x.name});m.bindPopup(popup(x),{maxWidth:340});m.on("click",()=>select(x.id,false));m.addTo(layer);state.markers.set(x.id,m)}}
function card(x){const c=COLORS[x.category]||"#169b7b";return `<button type="button" class="location-card ${state.selectedId===x.id?"is-active":""}" data-location-id="${esc(x.id)}" style="--category-color:${c}" aria-label="View ${esc(x.name)} on the map"><span class="card-icon">${esc(x.icon)}</span><span><span class="card-topline"><span><h3 class="card-title">${esc(x.name)}</h3><p class="card-meta">${esc(x.district)} · ${esc(x.municipality)}</p></span><span class="badge">${esc(x.category)}</span></span><p class="card-summary">${esc(x.summary)}</p><span class="chip-row">${x.opportunities.slice(0,3).map(i=>`<span class="chip">${esc(i)}</span>`).join("")}</span></span></button>`}
function render(){el.list.innerHTML=state.visible.map(card).join("");el.count.textContent=`${state.visible.length} location${state.visible.length===1?"":"s"}`;el.empty.hidden=state.visible.length!==0;el.list.querySelectorAll("[data-location-id]").forEach(b=>b.addEventListener("click",()=>select(b.dataset.locationId,true)))}
function filter(){const q=el.search.value.trim().toLowerCase(),d=el.district.value,c=el.category.value,v=el.verified.checked;state.visible=state.locations.filter(x=>{const hay=[x.name,x.district,x.municipality,x.category,x.summary,...x.opportunities,...x.assets].join(" ").toLowerCase();return(!q||hay.includes(q))&&(!d||x.district===d)&&(!c||x.category===c)&&(!v||!x.verification_status.toLowerCase().includes("verify before"))});if(!state.visible.some(x=>x.id===state.selectedId))state.selectedId=state.visible[0]?.id||null;addMarkers();render()}
function select(id,move){state.selectedId=id;render();const x=state.locations.find(i=>i.id===id),m=state.markers.get(id);if(!x||!m)return;if(move)map.flyTo([x.latitude,x.longitude],Math.max(map.getZoom(),9),{duration:.7});m.openPopup();el.list.querySelector(`[data-location-id="${CSS.escape(id)}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest"})}
function fit(){if(!state.visible.length)return;map.fitBounds(L.latLngBounds(state.visible.map(x=>[x.latitude,x.longitude])).pad(.18),{maxZoom:9})}
function populate(){[...new Set(state.locations.map(x=>x.district))].sort().forEach(v=>el.district.insertAdjacentHTML("beforeend",`<option value="${esc(v)}">${esc(v)}</option>`));[...new Set(state.locations.map(x=>x.category))].sort().forEach(v=>el.category.insertAdjacentHTML("beforeend",`<option value="${esc(v)}">${esc(v)}</option>`))}
function reset(){el.search.value="";el.district.value="";el.category.value="";el.verified.checked=false;filter();fit()}
async function init(){try{const r=await fetch("data/locations.json");if(!r.ok)throw new Error(`Data request failed: ${r.status}`);state.locations=await r.json();state.visible=[...state.locations];state.selectedId=state.locations[0]?.id||null;populate();filter();fit()}catch(e){console.error(e);el.empty.hidden=false;el.empty.textContent="The dataset could not be loaded. Run the project through a local web server instead of opening index.html directly."}}
[el.search,el.district,el.category,el.verified].forEach(c=>c.addEventListener("input",filter));el.reset.addEventListener("click",reset);el.fit.addEventListener("click",fit);init();
